/**
 * Medi Smart Interview Test
 * Medi Smart Interview Test endpoints
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserData { 
    id?: number;
    firstName?: string;
    lastName?: string;
    accountNumber?: string;
    bvn?: number;
    staffId?: string;
    department?: string;
    companyName?: string;
    companyAddress?: string;
    stateOfOrigin?: string;
}
